In [2]:
import numpy as np
print(np.__version__)

2.4.2


- 데이터 분석 : 수치형 변수의 요약, 통계, 시각화
- 이미지 처리 ai : 이미지 데이터
- 게임/시뮬레이션 : 시뮬레이션 구현 
- 머신러닝/ 딥러닝 : 금융,의료,실험 등등


In [5]:
arr = np.array([1,2,3,4,5])
print(arr)
arr.shape

[1 2 3 4 5]


(5,)

In [11]:
arr= np.array([[1,2,3],
              [4,5,6]])
arr.ndim

2

In [12]:
np.array(7).shape

()

In [13]:
np.array([7]).shape

(1,)

In [14]:
arr1 = np.array([1,2,3,4,5])
arr12 = np.array([[1,2,3,4,5],[1,2,3,4,56]])
arr1.shape,arr12.shape

((5,), (2, 5))

In [17]:
arr13=np.array([[1,2,3,4,5],[1,2,3,4,6],[1,2,3,4,6]])
arr13.shape

(3, 5)

In [18]:
# 리스트로부터 배열 생성
arr1 = np.array([1, 2, 3, 4, 5]) #arr1.shape : (5,0)
arr12 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]) #arr12.shape : (2,5)

# (3,5) 행렬 arr13 만들기

# 0으로 채워진 배열 생성
arr2 = np.zeros(5)

# 1로 채워진 배열 생성
arr3 = np.ones((3, 3))

# 1부터 10까지 2씩 증가하는 배열
range_arr = np.arange(1, 10, 2)  
print(range_arr)

 # 0부터 100까지 5개의 숫자를 균등 간격으로 생성
linspace_arr = np.linspace(0, 100, 5) 
print(linspace_arr)

# 2행 3열의 랜덤 값 배열 (0~1 사이)
random_arr = np.random.rand(2, 3) 
print(random_arr)

[1 3 5 7 9]
[  0.  25.  50.  75. 100.]
[[0.99508711 0.1456754  0.5587955 ]
 [0.04255615 0.14247723 0.49637476]]


# 넘파이랑 데이터 타입 

In [19]:
arr13.dtype

dtype('int64')

In [20]:
# 다양한 데이터 타입의 배열 생성
#dtype 속성; np.int32 상수, ‘int32’ 문자열 형식으로 지정
int_array = np.array([1, 2, 3], dtype=np.int32)
float_array = np.array([1.0, 2.0, 3.0], dtype=np.float64)
bool_array = np.array([True, False, True], dtype=np.bool_)

print("정수 배열의 dtype:", int_array.dtype)
print("실수 배열의 dtype:", float_array.dtype)
print("불리언 배열의 dtype:", bool_array.dtype)

정수 배열의 dtype: int32
실수 배열의 dtype: float64
불리언 배열의 dtype: bool


In [21]:
# 데이터 타입 변환 예제
float_arr = np.array([1.1, 2.2, 3.3])
int_arr = float_arr.astype(np.int32)  # 실수를 정수로 변환
print("변환 전:", float_arr, float_arr.dtype)
print("변환 후:", int_arr, int_arr.dtype)

변환 전: [1.1 2.2 3.3] float64
변환 후: [1 2 3] int32


In [22]:
arr_str = np.array(['1', '2', 'three'])  # 'three'는 숫자로 변환 불가
arr_int = arr_str.astype(int)  # 오류 발생

ValueError: invalid literal for int() with base 10: np.str_('three')

In [24]:
# 1차원 배열 생성
a = np.arange(12)
print(a)  # [ 0  1  2  3  4  5  6  7  8  9 10 11]

# 2차원 배열로 변환 (3x4)
b = a.reshape(3, 4)
print(b)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# 3차원 배열로 변환 (2x2x3)
c = a.reshape(2, 2, 3)
print(c)
# [[[ 0  1  2]
#   [ 3  4  5]]
#  [[ 6  7  8]
#   [ 9 10 11]]]


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr + 2)  # [3, 4, 5, 6, 7]
print(arr * 3)  # [3, 6, 9, 12, 15]
print(2 ** arr)  # [2, 4, 8, 16, 32]

[3 4 5 6 7]
[ 3  6  9 12 15]
[ 2  4  8 16 32]


In [ ]:
# 생산량 * 단가(이익률)=총 매출

In [25]:
import numpy as np

# 데이터를 NumPy 배열로 변환
prod_arr = np.array([100, 200, 150])
price_arr = np.array([50000, 30000, 40000])
margin_arr = np.array([0.2, 0.15, 0.25])

# 배열끼리 직접 곱하기 (Element-wise multiplication)
revenue_arr = prod_arr * price_arr * margin_arr

print(f"계산된 배열: {revenue_arr}")
print(f"총 매출 합계: {np.sum(revenue_arr):,.0f}원")

계산된 배열: [1000000.  900000. 1500000.]
총 매출 합계: 3,400,000원


In [26]:
# 일반 Python 반복문 vs NumPy 벡터화 연산 비교
import numpy as np
import time

# 큰 배열 생성
size = 1000000
arr1 = np.array(range(size))
arr2 = np.array(range(size))
result_list = [0] * size

# Python 반복문 방식
start_time = time.time()
for i in range(size):
    result_list[i] = arr1[i] + arr2[i]
python_time = time.time() - start_time

# NumPy 벡터화 연산 방식
start_time = time.time()
result_numpy = arr1 + arr2
numpy_time = time.time() - start_time

print(f"Python 반복문 실행 시간: {python_time:.4f}초")
print(f"NumPy 벡터화 연산 실행 시간: {numpy_time:.4f}초")
print(f"속도 향상: {python_time/numpy_time:.1f}배")

Python 반복문 실행 시간: 0.1965초
NumPy 벡터화 연산 실행 시간: 0.0010초
속도 향상: 193.9배


In [27]:
# 브로드캐스팅 예제
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
scalar = 2

# 배열과 스칼라의 연산
print("배열 * 스칼라:")
print(arr * scalar)
# [[ 2  4  6]
#  [ 8 10 12]]

# 1차원 배열과 2차원 배열의 연산
row = np.array([1, 0, 1])
print("\n2차원 배열 + 1차원 배열:")
print(arr + row)
# [[2 2 4]
#  [5 5 7]]

배열 * 스칼라:
[[ 2  4  6]
 [ 8 10 12]]

2차원 배열 + 1차원 배열:
[[2 2 4]
 [5 5 7]]


In [29]:
import numpy as np

# 1) np.arange(3) + 5
a = np.arange(3) + 5
print("1) np.arange(3) + 5")
print(a)
print()

# 2) np.ones((3, 3)) + np.arange(3)
b = np.ones((3, 3)) + np.arange(3)
print("2) np.ones((3, 3)) + np.arange(3)")
print(b)
print()

# 3) np.ones((3, 1)) + np.arange(3)
d = np.arange(3).reshape(3, 1) + np.arange(3)
print(d)

1) np.arange(3) + 5
[5 6 7]

2) np.ones((3, 3)) + np.arange(3)
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]

[[0 1 2]
 [1 2 3]
 [2 3 4]]


# 축 인덱싱 

In [31]:
# 2차원 배열 예제
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

# axis=0 방향 합계 (열 방향 합)
sum_axis0 = np.sum(arr_2d, axis=0)  # [5, 7, 9]

# axis=1 방향 합계 (행 방향 합)
sum_axis1 = np.sum(arr_2d, axis=1)  # [6, 15]

In [32]:
# 1차원 배열 인덱싱
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])    # 첫 번째 요소: 1
print(arr[-1])   # 마지막 요소: 5

# 2차원 배열 인덱싱
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(arr_2d[0, 1])    # 첫 번째 행, 두 번째 열: 2
print(arr_2d[1, -1])   # 두 번째 행, 마지막 열: 6

1
5
2
6


In [33]:
# 1차원 배열 슬라이싱
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr[2:5])    # [2 3 4]
print(arr[::2])    # [0 2 4]

# 2차원 배열 슬라이싱
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(arr_2d[:2, 1:3])    # 처음 두 행, 두 번째와 세 번째 열
# [[2 3]
#  [6 7]]

[2 3 4]
[0 2 4]
[[2 3]
 [6 7]]


In [37]:
import numpy as np

matrix = np.arange(36).reshape(6, 6)
arr = np.array([matrix for _ in range(4)])

print(arr)
print(arr.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
(4, 6, 6)


In [38]:
arr[0,:3,:3]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

# 고급인덱싱

In [39]:
# Boolean 인덱싱 
arr = np.array([1,2,3,4,5])
bool_array=np.array([True,False,True,False,True])
print(arr[bool_array])

[1 3 5]


In [40]:
mask = arr >3
mask

array([False, False, False,  True,  True])

In [42]:
arr[mask]=0


In [ ]:
arr

array([1, 2, 3, 0, 0])

In [ ]:
daily_returns=np.array([-])